version: "3.7"
services:
  challenge-proxy:
    build:
      context: .docker/reverse-proxy
      dockerfile: Dockerfile
    container_name: challenge-proxy
    hostname: challenge-proxy
    depends_on:
      - challenge-api
    ports:
      - "8000:80"
    restart: always
    networks:
      - challenge-network

  challenge-api:
    build:
      context: ./challenge-api
      dockerfile: Dockerfile
    container_name: challenge-api
    hostname: challenge-api
    depends_on:
      - challenge-cache
    env_file:
      - ./challenge-api/.env
    ports:
      - "3500"
    volumes:
      - ./challenge-api:/app
      - node_modules:/app/node_modules
    command: npm start
    #command: tail -F anything
    networks:
      - challenge-network


  challenge-cache:
    image: docker.io/bitnami/redis:7.0
    container_name: challenge-cache
    hostname: challenge-cache
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6500:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - challenge-network

networks:
  challenge-network:
        driver: bridge

volumes:
  node_modules:
  redis_data:
    driver: local
